{
  "table": "imported_invoices",
  "timestamp": "2025-08-27T18:28:38.967Z",
  "records": [
    {
      "id": 1,
      "log_id": 1,
      "invoice_id": null,
      "original_file_name": "FE359_901282814_SOLUCIONES_EN_MADERA_OLIVERA_SAS.pdf",
      "file_type": "pdf",
      "file_size": 121978,
      "file_path": "uploads/FE359_901282814_SOLUCIONES_EN_MADERA_OLIVERA_SAS.pdf",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": 240,
      "base_file_name": "FE359_901282814_SOLUCIONES_EN_MADERA_OLIVERA_SAS",
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "emisor": "901282814",
        "source": "python_rpa",
        "configId": 5,
        "processed": false,
        "totalValue": "3271981.67",
        "linkedToXml": true,
        "documentNumber": "FE359"
      },
      "created_at": "2025-08-25T23:58:13.667Z"
    },
    {
      "id": 2,
      "log_id": 1,
      "invoice_id": null,
      "original_file_name": "F2BC682_900916849_BCP_INGENIEROS_CIVILES_SAS.pdf",
      "file_type": "pdf",
      "file_size": 81783,
      "file_path": "uploads/F2BC682_900916849_BCP_INGENIEROS_CIVILES_SAS.pdf",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": 239,
      "base_file_name": "F2BC682_900916849_BCP_INGENIEROS_CIVILES_SAS",
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "emisor": "900916849",
        "source": "python_rpa",
        "configId": 5,
        "processed": false,
        "totalValue": "81783",
        "linkedToXml": true,
        "documentNumber": "F2BC682"
      },
      "created_at": "2025-08-25T23:58:15.006Z"
    },
    {
      "id": 3,
      "log_id": 1,
      "invoice_id": null,
      "original_file_name": "BGA12267_890213074_AMV_SAS.pdf",
      "file_type": "pdf",
      "file_size": 16190,
      "file_path": "uploads/BGA12267_890213074_AMV_SAS.pdf",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": 237,
      "base_file_name": "BGA12267_890213074_AMV_SAS",
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "emisor": "890213074",
        "source": "python_rpa",
        "configId": 5,
        "processed": false,
        "totalValue": "16190",
        "linkedToXml": true,
        "documentNumber": "BGA12267"
      },
      "created_at": "2025-08-25T23:58:17.377Z"
    },
    {
      "id": 4,
      "log_id": 1,
      "invoice_id": null,
      "original_file_name": "ARQ5294_900348035_DISEÑOS_ARQUITECTONICOS_G.pdf",
      "file_type": "pdf",
      "file_size": 121982,
      "file_path": "uploads/ARQ5294_900348035_DISEÑOS_ARQUITECTONICOS_G.pdf",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": 236,
      "base_file_name": "ARQ5294_900348035_DISEÑOS_ARQUITECTONICOS_G",
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "emisor": "900348035",
        "source": "python_rpa",
        "configId": 5,
        "processed": false,
        "totalValue": "121982",
        "linkedToXml": true,
        "documentNumber": "ARQ5294"
      },
      "created_at": "2025-08-26T00:05:39.153Z"
    },
    {
      "id": 5,
      "log_id": 1,
      "invoice_id": null,
      "original_file_name": "FEPG799160_900570964_ULTRACEM_S_A_S.pdf",
      "file_type": "pdf",
      "file_size": 156340,
      "file_path": "uploads/FEPG799160_900570964_ULTRACEM_S_A_S.pdf",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": 233,
      "base_file_name": "FEPG799160_900570964_ULTRACEM_S_A_S",
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "emisor": "900570964",
        "source": "python_rpa",
        "configId": 5,
        "processed": false,
        "totalValue": "156340",
        "linkedToXml": true,
        "documentNumber": "FEPG799160"
      },
      "created_at": "2025-08-26T00:05:40.429Z"
    },
    {
      "id": 6,
      "log_id": 1,
      "invoice_id": null,
      "original_file_name": "FEPG799271_900570964_ULTRACEM_S_A_S.pdf",
      "file_type": "pdf",
      "file_size": 156818,
      "file_path": "uploads/FEPG799271_900570964_ULTRACEM_S_A_S.pdf",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": 235,
      "base_file_name": "FEPG799271_900570964_ULTRACEM_S_A_S",
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "emisor": "900570964",
        "source": "python_rpa",
        "configId": 5,
        "processed": false,
        "totalValue": "156818",
        "linkedToXml": true,
        "documentNumber": "FEPG799271"
      },
      "created_at": "2025-08-26T00:05:41.487Z"
    },
    {
      "id": 7,
      "log_id": 1,
      "invoice_id": null,
      "original_file_name": "F2BC681_900916849_BCP_INGENIEROS_CIVILES_SAS.pdf",
      "file_type": "pdf",
      "file_size": 81702,
      "file_path": "uploads/F2BC681_900916849_BCP_INGENIEROS_CIVILES_SAS.pdf",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": 231,
      "base_file_name": "F2BC681_900916849_BCP_INGENIEROS_CIVILES_SAS",
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "emisor": "900916849",
        "source": "python_rpa",
        "configId": 5,
        "processed": false,
        "totalValue": "81702",
        "linkedToXml": true,
        "documentNumber": "F2BC681"
      },
      "created_at": "2025-08-26T00:05:59.005Z"
    },
    {
      "id": 8,
      "log_id": 1,
      "invoice_id": null,
      "original_file_name": "FEPG799159_900570964_ULTRACEM_S_A_S.pdf",
      "file_type": "pdf",
      "file_size": 156327,
      "file_path": "uploads/FEPG799159_900570964_ULTRACEM_S_A_S.pdf",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": 232,
      "base_file_name": "FEPG799159_900570964_ULTRACEM_S_A_S",
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "emisor": "900570964",
        "source": "python_rpa",
        "configId": 5,
        "processed": false,
        "totalValue": "156327",
        "linkedToXml": true,
        "documentNumber": "FEPG799159"
      },
      "created_at": "2025-08-26T00:06:01.490Z"
    },
    {
      "id": 9,
      "log_id": 1,
      "invoice_id": null,
      "original_file_name": "ARQ5293_900348035_DISEÑOS_ARQUITECTONICOS_G.pdf",
      "file_type": "pdf",
      "file_size": 121230,
      "file_path": "uploads/ARQ5293_900348035_DISEÑOS_ARQUITECTONICOS_G.pdf",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": 234,
      "base_file_name": "ARQ5293_900348035_DISEÑOS_ARQUITECTONICOS_G",
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "emisor": "900348035",
        "source": "python_rpa",
        "configId": 5,
        "processed": false,
        "totalValue": "121230",
        "linkedToXml": true,
        "documentNumber": "ARQ5293"
      },
      "created_at": "2025-08-26T00:06:03.129Z"
    },
    {
      "id": 10,
      "log_id": 1,
      "invoice_id": null,
      "original_file_name": "F2BC683_900916849_BCP_INGENIEROS_CIVILES_SAS.pdf",
      "file_type": "pdf",
      "file_size": 81735,
      "file_path": "uploads/F2BC683_900916849_BCP_INGENIEROS_CIVILES_SAS.pdf",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": 238,
      "base_file_name": "F2BC683_900916849_BCP_INGENIEROS_CIVILES_SAS",
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "emisor": "900916849",
        "source": "python_rpa",
        "configId": 5,
        "processed": false,
        "totalValue": "81735",
        "linkedToXml": true,
        "documentNumber": "F2BC683"
      },
      "created_at": "2025-08-26T00:06:05.530Z"
    },
    {
      "id": 16,
      "log_id": 6,
      "invoice_id": null,
      "original_file_name": "B1197726_892300678_ETICOS_SAS.zip",
      "file_type": "zip",
      "file_size": null,
      "file_path": "uploads/pdfs/B1197726_892300678_ETICOS_SAS.zip",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": null,
      "base_file_name": null,
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "source": "recovery_manual",
        "configId": 5,
        "processed": false
      },
      "created_at": "2025-08-27T16:45:23.329Z"
    },
    {
      "id": 17,
      "log_id": 6,
      "invoice_id": null,
      "original_file_name": "CONS5721_901220439_CONSTRUSOLUCIONES_F&B_SAS.zip",
      "file_type": "zip",
      "file_size": null,
      "file_path": "uploads/pdfs/CONS5721_901220439_CONSTRUSOLUCIONES_F&B_SAS.zip",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": null,
      "base_file_name": null,
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "source": "recovery_manual",
        "configId": 5,
        "processed": false
      },
      "created_at": "2025-08-27T16:45:23.329Z"
    },
    {
      "id": 18,
      "log_id": 6,
      "invoice_id": null,
      "original_file_name": "CONS5724_901220439_CONSTRUSOLUCIONES_F&B_SAS.zip",
      "file_type": "zip",
      "file_size": null,
      "file_path": "uploads/pdfs/CONS5724_901220439_CONSTRUSOLUCIONES_F&B_SAS.zip",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": null,
      "base_file_name": null,
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "source": "recovery_manual",
        "configId": 5,
        "processed": false
      },
      "created_at": "2025-08-27T16:45:23.329Z"
    },
    {
      "id": 19,
      "log_id": 6,
      "invoice_id": null,
      "original_file_name": "FEPB201314_900570964_ULTRACEM_S_A_S.zip",
      "file_type": "zip",
      "file_size": null,
      "file_path": "uploads/pdfs/FEPB201314_900570964_ULTRACEM_S_A_S.zip",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": null,
      "base_file_name": null,
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "source": "recovery_manual",
        "configId": 5,
        "processed": false
      },
      "created_at": "2025-08-27T16:45:23.329Z"
    },
    {
      "id": 20,
      "log_id": 6,
      "invoice_id": null,
      "original_file_name": "FEPG799545_900570964_ULTRACEM_S_A_S.zip",
      "file_type": "zip",
      "file_size": null,
      "file_path": "uploads/pdfs/FEPG799545_900570964_ULTRACEM_S_A_S.zip",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": null,
      "base_file_name": null,
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "source": "recovery_manual",
        "configId": 5,
        "processed": false
      },
      "created_at": "2025-08-27T16:45:23.329Z"
    },
    {
      "id": 21,
      "log_id": 6,
      "invoice_id": null,
      "original_file_name": "FEPG799546_900570964_ULTRACEM_S_A_S.zip",
      "file_type": "zip",
      "file_size": null,
      "file_path": "uploads/pdfs/FEPG799546_900570964_ULTRACEM_S_A_S.zip",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": null,
      "base_file_name": null,
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "source": "recovery_manual",
        "configId": 5,
        "processed": false
      },
      "created_at": "2025-08-27T16:45:35.533Z"
    },
    {
      "id": 22,
      "log_id": 6,
      "invoice_id": null,
      "original_file_name": "FEPG799548_900570964_ULTRACEM_S_A_S.zip",
      "file_type": "zip",
      "file_size": null,
      "file_path": "uploads/pdfs/FEPG799548_900570964_ULTRACEM_S_A_S.zip",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": null,
      "base_file_name": null,
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "source": "recovery_manual",
        "configId": 5,
        "processed": false
      },
      "created_at": "2025-08-27T16:45:35.533Z"
    },
    {
      "id": 23,
      "log_id": 6,
      "invoice_id": null,
      "original_file_name": "FEPG799636_900570964_ULTRACEM_S_A_S.zip",
      "file_type": "zip",
      "file_size": null,
      "file_path": "uploads/pdfs/FEPG799636_900570964_ULTRACEM_S_A_S.zip",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": null,
      "base_file_name": null,
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "source": "recovery_manual",
        "configId": 5,
        "processed": false
      },
      "created_at": "2025-08-27T16:45:35.533Z"
    },
    {
      "id": 24,
      "log_id": 6,
      "invoice_id": null,
      "original_file_name": "FEPG799641_900570964_ULTRACEM_S_A_S.zip",
      "file_type": "zip",
      "file_size": null,
      "file_path": "uploads/pdfs/FEPG799641_900570964_ULTRACEM_S_A_S.zip",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": null,
      "base_file_name": null,
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "source": "recovery_manual",
        "configId": 5,
        "processed": false
      },
      "created_at": "2025-08-27T16:45:35.533Z"
    },
    {
      "id": 25,
      "log_id": 6,
      "invoice_id": null,
      "original_file_name": "FEV41934_79786664_GUILLERMO_ENRIQUE_ESCOLAR_FLOREZ.zip",
      "file_type": "zip",
      "file_size": null,
      "file_path": "uploads/pdfs/FEV41934_79786664_GUILLERMO_ENRIQUE_ESCOLAR_FLOREZ.zip",
      "erp_document_id": null,
      "matched_file_id": null,
      "linked_invoice_id": null,
      "base_file_name": null,
      "is_data_source": false,
      "processing_status": "downloaded",
      "downloaded_at": null,
      "processed_at": null,
      "metadata": {
        "source": "recovery_manual",
        "configId": 5,
        "processed": false
      },
      "created_at": "2025-08-27T16:45:35.533Z"
    }
  ]
}